# -*- coding: utf-8 -*-
"""variant_calling_pipeline_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYGdPji0e1AX3T321yGbdyehRIcq4N0N

# 🧬 Variant Calling Pipeline — BRCA1 (Google Colab)

This notebook implements a **variant calling pipeline** for Illumina paired-end sequencing data using the BRCA1 gene as a case study.

Two complementary variant calling approaches are provided side-by-side:

| Approach | Caller | Best for |
|----------|--------|----------|
| **A** | GATK HaplotypeCaller | Clinical / germline (GATK Best Practices) |
| **B** | FreeBayes | Research / flexible allele-frequency analysis |

---

## 📚 Pipeline overview

```
Raw FASTQ (paired-end)
    │
    ├── [Step 1] Download data            → Entrez (chr17 GRCh38) + GitHub (BRCA1)
    ├── [Step 2] Quality Control          → FastQC + MultiQC
    ├── [Step 3] Trimming                 → fastp (Q≥20)
    ├── [Step 4] Alignment                → BWA-MEM → sorted, indexed BAM
    ├── [Step 5A] Variant Calling — GATK  → HaplotypeCaller → GVCF → VCF
    ├── [Step 5B] Variant Calling — Free  → FreeBayes → VCF
    ├── [Step 6] Normalization (FreeBayes)→ rename chr + bcftools norm
    ├── [Step 7] Annotation               → bcftools annotate + ClinVar mini
    └── [Step 8] Summary Statistics       → bcftools stats (SNP/INDEL, Ts/Tv)
```

## 🗂️ Input data

- **Samples**: BRCA1_WT, BRCA1_185delAG, BRCA1_c.5266dupC (from [oncogensus/Curso-RSG-Brazil](https://github.com/oncogensus/Curso-RSG-Brazil))
- **Reference**: chromosome 17 GRCh38 (NC_000017.11, downloaded via Entrez)
- **Annotation**: ClinVar mini database (provided in the repository)

> 💡 Run cells sequentially. After **Step 0**, wait for the Colab kernel to restart before continuing.

## ⚙️ Step 0 — Environment setup (condacolab + mamba)
"""

# Install condacolab and initialise mamba (run once per Colab session)
!pip install --upgrade --force-reinstall zstandard --quiet
!pip install -q condacolab

import condacolab
condacolab.install()

# Remove version pins that may cause conflicts
!sed -i '/cudatoolkit/d' /usr/local/conda-meta/pinned
!sed -i '/python/d' /usr/local/conda-meta/pinned

# Install curl (needed by some tools)
!mamba install -c conda-forge curl -y --quiet

!echo "Setup complete"
!mamba env list

"""## 📥 Step 1 — Download reference genome and sequencing data"""

# Create environment to download the reference genome via Entrez (NCBI)
!mamba create -n entrez -y --quiet
!mamba install -n entrez -c bioconda entrez-direct -y --quiet

# Create output folders
!mkdir -p refGen data

# Download chromosome 17 (GRCh38)
!echo "# Downloading chromosome 17 (GRCh38) via Entrez"
!mamba run -n entrez bash -c \
  'esearch -db nucleotide -query "NC_000017.11" | efetch -format fasta > ./refGen/chr17_GRCh38.fasta'

!ls -lh ./refGen/

# Clone the course repository with BRCA1 FASTQ files and ClinVar mini database
!echo "# Cloning BRCA1 data from GitHub"
!git clone https://github.com/oncogensus/Curso-RSG-Brazil.git ./brca1
!ls ./brca1/

"""## 🔬 Step 2 — Quality control (FastQC + MultiQC)"""

# Create environment with FastQC, MultiQC and fastp
!mamba create -n quality -c bioconda fastqc multiqc fastp -y --quiet

!mkdir -p fastqc multiqc trimmed

# Run FastQC on all samples
!echo "# Running FastQC"
!mamba run -n quality fastqc ./brca1/*.fq.gz -o ./fastqc --quiet

# Run MultiQC to aggregate reports
!echo "# Running MultiQC"
!mamba run -n quality multiqc ./fastqc -o ./multiqc --quiet

# Download MultiQC report
from google.colab import files
files.download("./multiqc/multiqc_report.html")

"""## ✂️ Step 3 — Read trimming (fastp, Q≥20)"""

# Trim all three samples (Q≥20, auto adapter detection)
!echo "# Trimming BRCA1_WT"
!mamba run -n quality fastp \
  -i ./brca1/BRCA1_WT_R1.fq.gz \
  -I ./brca1/BRCA1_WT_R2.fq.gz \
  --detect_adapter_for_pe \
  -o ./trimmed/BRCA1_WT_R1_trim.fq.gz \
  -O ./trimmed/BRCA1_WT_R2_trim.fq.gz \
  -h ./trimmed/BRCA1_WT_fastp.html \
  --qualified_quality_phred 20 --thread 4

!echo "# Trimming BRCA1_185delAG"
!mamba run -n quality fastp \
  -i ./brca1/BRCA1_185delAG_R1.fq.gz \
  -I ./brca1/BRCA1_185delAG_R2.fq.gz \
  --detect_adapter_for_pe \
  -o ./trimmed/BRCA1_185delAG_R1_trim.fq.gz \
  -O ./trimmed/BRCA1_185delAG_R2_trim.fq.gz \
  -h ./trimmed/BRCA1_185delAG_fastp.html \
  --qualified_quality_phred 20 --thread 4

!echo "# Trimming BRCA1_c.5266dupC"
!mamba run -n quality fastp \
  -i ./brca1/BRCA1_c.5266dupC_R1.fq.gz \
  -I ./brca1/BRCA1_c.5266dupC_R2.fq.gz \
  --detect_adapter_for_pe \
  -o ./trimmed/BRCA1_c.5266dupC_R1_trim.fq.gz \
  -O ./trimmed/BRCA1_c.5266dupC_R2_trim.fq.gz \
  -h ./trimmed/BRCA1_c.5266dupC_fastp.html \
  --qualified_quality_phred 20 --thread 4

!ls -lh ./trimmed/*.fq.gz

"""## 🧭 Step 4 — Alignment (BWA-MEM → sorted, indexed BAM)

**BWA-MEM** aligns reads to the reference genome.  
**Samtools** converts SAM to BAM, sorts by coordinate, and creates an index.

Read groups (`-R`) are required by GATK and help track sample identity.

> ⚠️ After alignment we also extract **only mapped reads** (`-F 4`) to reduce file size and avoid issues in variant calling.
"""

# Create environments for BWA and Samtools
!mamba create -n bwa -c bioconda bwa -y --quiet
!mamba create -n samtools -c bioconda samtools -y --quiet

# Index the reference genome
!echo "# Indexing reference genome"
!mamba run -n bwa bwa index -p ./refGen/chr17_GRCh38 ./refGen/chr17_GRCh38.fasta

# Create Samtools FASTA index (required by GATK)
!mamba run -n samtools samtools faidx ./refGen/chr17_GRCh38.fasta

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Align each sample: BWA-MEM → sort → index → flagstat
# mkdir -p aligned
# 
# for SAMPLE in BRCA1_WT BRCA1_185delAG BRCA1_c.5266dupC; do
#   R1="./trimmed/${SAMPLE}_R1_trim.fq.gz"
#   R2="./trimmed/${SAMPLE}_R2_trim.fq.gz"
#   RAW_BAM="./aligned/${SAMPLE}.bam"
#   SORTED_BAM="./aligned/${SAMPLE}_sorted.bam"
#   MAPPED_BAM="./aligned/${SAMPLE}_mapped.bam"
# 
#   echo "--- Aligning ${SAMPLE} ---"
#   mamba run -n bwa bwa mem -M -t 4 \
#     -R "@RG\tID:${SAMPLE}\tSM:${SAMPLE}\tPL:ILLUMINA\tLB:${SAMPLE}_lib1\tPU:${SAMPLE}_unit1" \
#     ./refGen/chr17_GRCh38 $R1 $R2 -o $RAW_BAM
# 
#   echo "--- Sorting ${SAMPLE} ---"
#   mamba run -n samtools samtools sort -o $SORTED_BAM $RAW_BAM
# 
#   echo "--- Indexing ${SAMPLE} ---"
#   mamba run -n samtools samtools index $SORTED_BAM
# 
#   echo "--- Flagstat ${SAMPLE} ---"
#   mamba run -n samtools samtools flagstat $SORTED_BAM
# 
#   echo "--- Extracting mapped reads only (removing flag 4) ---"
#   mamba run -n samtools samtools view -b -F 4 -o $MAPPED_BAM $SORTED_BAM
#   mamba run -n samtools samtools index $MAPPED_BAM
# done
# 
# echo "Aligned BAM files:"
# ls -lh ./aligned/*_mapped.bam

"""## 🧪 Step 5A — Variant Calling: GATK HaplotypeCaller

**Workflow:** HaplotypeCaller (GVCF) → CombineGVCFs → GenotypeGVCFs → VariantFiltration
"""

# Install GATK4
!mamba create -n gatk -c bioconda gatk4 -y --quiet

# Create sequence dictionary (required by GATK)
!mamba run -n gatk gatk CreateSequenceDictionary \
  -R /content/refGen/chr17_GRCh38.fasta \
  -O /content/refGen/chr17_GRCh38.dict

!mkdir -p variants/gatk

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # HaplotypeCaller in GVCF mode for each sample
# for SAMPLE in BRCA1_WT BRCA1_185delAG BRCA1_c.5266dupC; do
#   echo "--- HaplotypeCaller: ${SAMPLE} ---"
#   mamba run -n gatk gatk HaplotypeCaller \
#     -R /content/refGen/chr17_GRCh38.fasta \
#     -I ./aligned/${SAMPLE}_mapped.bam \
#     -O ./variants/gatk/${SAMPLE}.g.vcf.gz \
#     -ERC GVCF --verbosity ERROR
# done

# Combine GVCFs → joint genotyping → filter
!echo "# CombineGVCFs"
!mamba run -n gatk gatk CombineGVCFs \
  -R /content/refGen/chr17_GRCh38.fasta \
  -V ./variants/gatk/BRCA1_WT.g.vcf.gz \
  -V ./variants/gatk/BRCA1_185delAG.g.vcf.gz \
  -V ./variants/gatk/BRCA1_c.5266dupC.g.vcf.gz \
  -O ./variants/gatk/cohort.g.vcf.gz --verbosity ERROR

!echo "# GenotypeGVCFs"
!mamba run -n gatk gatk GenotypeGVCFs \
  -R /content/refGen/chr17_GRCh38.fasta \
  -V ./variants/gatk/cohort.g.vcf.gz \
  -O ./variants/gatk/cohort.vcf.gz --verbosity ERROR

!echo "# VariantFiltration (QD < 2, FS > 60, MQ < 40)"
!mamba run -n gatk gatk VariantFiltration \
  -R /content/refGen/chr17_GRCh38.fasta \
  -V ./variants/gatk/cohort.vcf.gz \
  -O ./variants/gatk/cohort_filtered.vcf.gz \
  --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0" \
  --filter-name "GATK_filter" --verbosity ERROR

!echo "# GATK VCF preview:"
!zcat ./variants/gatk/cohort_filtered.vcf.gz | grep -v "^##" | head -20

"""## 🧪 Step 5B — Variant Calling: FreeBayes

**Workflow:** FreeBayes (multi-BAM) → bcftools filter (QUAL≥20)
"""

# Install FreeBayes and bcftools
!mamba create -n freebayes -c bioconda freebayes bcftools -y --quiet

!mkdir -p variants/freebayes

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # FreeBayes: joint multi-sample calling from all mapped BAMs at once
# mamba run -n freebayes freebayes \
#   -f ./refGen/chr17_GRCh38.fasta \
#   ./aligned/BRCA1_WT_mapped.bam \
#   ./aligned/BRCA1_185delAG_mapped.bam \
#   ./aligned/BRCA1_c.5266dupC_mapped.bam > ./variants/freebayes/cohort_freebayes.vcf
# 
# mamba run -n freebayes bcftools index -t ./variants/freebayes/cohort_freebayes.vcf
# 
# echo "# Filtering: QUAL >= 20, SNPs and INDELs only"
# mamba run -n freebayes bash -c \
#   'bcftools view -v snps,indels ./variants/freebayes/cohort_freebayes.vcf | \
#    bcftools filter -i "QUAL>=20" -Oz -o ./variants/freebayes/cohort_freebayes_filtered.vcf.gz'
# 
# mamba run -n freebayes bcftools index -t ./variants/freebayes/cohort_freebayes_filtered.vcf.gz
# 
# echo "# FreeBayes VCF preview:"
# zcat ./variants/freebayes/cohort_freebayes_filtered.vcf.gz | grep -v "^##" | head -10

"""## 🔧 Step 6 — Normalise FreeBayes VCF for annotation

> **Why is this step needed?**
>
> The `bcftools annotate` command matches variants by **exact position + chromosome name + allele**.  
> Two differences between the FreeBayes output and the ClinVar mini database break this matching:
>
> | Issue | FreeBayes output | ClinVar mini expects |
> |-------|-----------------|----------------------|
> | Chromosome name | `17` (from Entrez FASTA header) | `chr17` |
> | INDEL representation | May differ (right-aligned) | Left-aligned (bcftools norm) |
>
> This step fixes both issues before annotation, so FreeBayes variants receive the same ClinVar IDs as GATK.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Create a chromosome name mapping file: 17 → chr17
# echo "17	chr17" > /tmp/chr_rename.txt
# 
# # Rename chromosome names (17 → chr17)
# mamba run -n freebayes bcftools annotate \
#   --rename-chrs /tmp/chr_rename.txt \
#   ./variants/freebayes/cohort_freebayes_filtered.vcf.gz \
#   -Oz -o ./variants/freebayes/cohort_freebayes_chr.vcf.gz
# 
# mamba run -n freebayes bcftools index -t ./variants/freebayes/cohort_freebayes_chr.vcf.gz
# 
# # Normalise INDEL representation (left-align + split multiallelic)
# mamba run -n freebayes bcftools norm \
#   -m-any \
#   -f ./refGen/chr17_GRCh38.fasta \
#   ./variants/freebayes/cohort_freebayes_chr.vcf.gz \
#   -Oz -o ./variants/freebayes/cohort_freebayes_norm.vcf.gz
# 
# mamba run -n freebayes bcftools index -t ./variants/freebayes/cohort_freebayes_norm.vcf.gz
# 
# echo "# Normalised FreeBayes VCF preview:"
# zcat ./variants/freebayes/cohort_freebayes_norm.vcf.gz | grep -v "^##" | head -10

"""## 🧬 Step 7 — Variant annotation (bcftools + ClinVar mini)

`bcftools annotate` matches variants by chromosome + position + allele and adds:
- **ID**: ClinVar variant ID or rsID
- **INFO**: clinical significance, gene name, condition
"""

# Install bcftools in its own environment
!mamba create -n bcftools -c bioconda bcftools -y --quiet

!mkdir -p annotated

# --- Annotate GATK output ---
!echo "# Annotating GATK VCF"
!mamba run -n bcftools bcftools annotate \
  -a ./brca1/clinvar_mini.vcf.gz \
  -c ID,INFO \
  ./variants/gatk/cohort_filtered.vcf.gz \
  -o ./annotated/cohort_gatk_annotated.vcf

# --- Annotate normalised FreeBayes output ---
!echo "# Annotating FreeBayes VCF (normalised)"
!mamba run -n bcftools bcftools annotate \
  -a ./brca1/clinvar_mini.vcf.gz \
  -c ID,INFO \
  ./variants/freebayes/cohort_freebayes_norm.vcf.gz \
  -o ./annotated/cohort_freebayes_annotated.vcf

!echo "# Annotated GATK VCF:"
!grep -v "^##" ./annotated/cohort_gatk_annotated.vcf | head -20

!echo "# Annotated FreeBayes VCF:"
!grep -v "^##" ./annotated/cohort_freebayes_annotated.vcf | head -20

"""## 📊 Step 8 — Summary statistics (bcftools stats)

`bcftools stats` computes:
- Total SNPs and INDELs
- Transition/Transversion ratio (Ts/Tv) — expected ~2.8–3.2 for WES
- Per-sample depth and genotype counts
"""

!echo "=== GATK VCF Statistics ==="
!mamba run -n bcftools bcftools stats \
  ./variants/gatk/cohort_filtered.vcf.gz | grep -E "^(SN|TSTV)" | head -20

!echo "=== FreeBayes VCF Statistics ==="
!mamba run -n bcftools bcftools stats \
  ./variants/freebayes/cohort_freebayes_norm.vcf.gz | grep -E "^(SN|TSTV)" | head -20

# Side-by-side comparison using Python
import subprocess

def get_stats(vcf_path):
    result = subprocess.run(
        f"mamba run -n bcftools bcftools stats {vcf_path}",
        shell=True, capture_output=True, text=True
    )
    stats = {}
    for line in result.stdout.split("\n"):
        if line.startswith("SN"):
            parts = line.split("\t")
            if len(parts) >= 4:
                stats[parts[2].strip().rstrip(":")] = parts[3].strip()
    return stats

gatk_stats = get_stats("./variants/gatk/cohort_filtered.vcf.gz")
fb_stats   = get_stats("./variants/freebayes/cohort_freebayes_norm.vcf.gz")

keys = ["number of samples", "number of records", "number of SNPs",
        "number of indels", "number of multiallelic sites", "number of MNPs"]

print(f"{'Metric':<35} {'GATK':>12} {'FreeBayes':>12}")
print("-" * 60)
for k in keys:
    print(f"{k:<35} {gatk_stats.get(k,'N/A'):>12} {fb_stats.get(k,'N/A'):>12}")

"""## 🎉 Pipeline complete!

| Step | Tool | Output |
|------|------|--------|
| Quality Control | FastQC + MultiQC | HTML reports |
| Trimming | fastp | Cleaned FASTQ |
| Alignment | BWA-MEM + Samtools | Sorted, indexed BAM |
| Variant Calling A | GATK HaplotypeCaller | `cohort_filtered.vcf.gz` |
| Variant Calling B | FreeBayes + bcftools | `cohort_freebayes_filtered.vcf.gz` |
| Normalisation | bcftools rename + norm | `cohort_freebayes_norm.vcf.gz` |
| Annotation | bcftools + ClinVar mini | Annotated VCF (both callers) |
| Statistics | bcftools stats | SNP/INDEL counts, Ts/Tv |

```
├── fastqc/               # Per-sample FastQC reports
├── multiqc/              # Aggregated MultiQC report
├── trimmed/              # Trimmed FASTQ files
├── aligned/              # Sorted, indexed, mapped BAM files
├── variants/
│   ├── gatk/             # GATK results
│   └── freebayes/        # FreeBayes results + normalised VCF
└── annotated/            # VCF files annotated with ClinVar (both callers)
```

### 🔗 References
- [GATK Best Practices](https://gatk.broadinstitute.org/hc/en-us/sections/360007226651)
- [FreeBayes GitHub](https://github.com/freebayes/freebayes)
- [bcftools documentation](https://www.htslib.org/doc/bcftools.html)
- [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/)
- [Original RSG Brazil 2026 notebook](https://github.com/oncogensus/Curso-RSG-Brazil)
"""