# -*- coding: utf-8 -*-
"""variant-pipe-run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kG5AMKrUsNGNeTy5kPV1eiO4skFaU7WQ

# 🧬 Variant Calling Pipeline — BRCA1 (Google Colab)

This notebook implements a **variant calling pipeline** for Illumina paired-end sequencing data using the BRCA1 gene as a case study.

Two complementary variant calling approaches are provided side-by-side:

| Approach | Caller | Best for |
|----------|--------|----------|
| **A** | GATK HaplotypeCaller | Clinical / germline (GATK Best Practices) |
| **B** | FreeBayes | Research / flexible allele-frequency analysis |

---

## Input data

- **Samples**: BRCA1_WT, BRCA1_185delAG, BRCA1_c.5266dupC
- **Reference**: from [oncogensus/Curso-RSG-Brazil](https://github.com/oncogensus/Curso-RSG-Brazil)
- **Data ref**: chromosome 17 GRCh38 (NC_000017.11, downloaded via Entrez)  
- **Annotation**: ClinVar mini database (provided in the repository)  

> 💡 **Google Colab**: All commands use `!` to run shell commands. Environments are managed with **mamba** via `condacolab`.

# STEP 0 — SETUP
Step 0 — Environment setup (condacolab + mamba)

**Mamba** is a fast conda-compatible package manager widely used in bioinformatics.  

`condacolab` installs mamba inside Google Colab so we can create isolated environments for each tool.

Install condacolab and initialise mamba (run once per Colab session)
"""

!pip install --upgrade --force-reinstall zstandard --quiet
!pip install -q condacolab

import condacolab
condacolab.install()

# Remove version pins that may cause conflicts
!sed -i '/cudatoolkit/d' /usr/local/conda-meta/pinned
!sed -i '/python/d' /usr/local/conda-meta/pinned

# Install curl (needed by some tools)
!mamba install -c conda-forge curl -y --quiet

"""# STEP 1 — DOWNLOAD DATA

Step 1 — Download reference genome and sequencing data

We will use **chromosome 17 (GRCh38)** as the reference and three BRCA1 samples:

- `BRCA1_WT` — wild-type (no mutations)  
- `BRCA1_185delAG` — pathogenic deletion variant  
- `BRCA1_c.5266dupC` — pathogenic duplication variant
"""

# Create environment to download the reference genome via Entrez (NCBI)
!mamba create -n entrez -y --quiet
!mamba install -n entrez -c bioconda entrez-direct -y --quiet

# Create output folders
!mkdir -p refGen data

# Download chromosome 17 (GRCh38)
!echo "#Downloading chromosome 17 (GRCh38) via Entrez"
!mamba run -n entrez bash -c 'esearch -db nucleotide -query "NC_000017.11" | efetch -format fasta > ./refGen/chr17_GRCh38.fasta'

!ls -lh ./refGen/

# Clone the course repository with BRCA1 FASTQ files
!echo "#Cloning BRCA1 data from GitHub"
!git clone https://github.com/oncogensus/Curso-RSG-Brazil.git ./brca1

!ls ./brca1/

"""# STEP 2 — QUALITY CONTROL

Step 2 — Quality control (FastQC + MultiQC)

**FastQC** generates per-sample quality reports. **MultiQC** aggregates them into a single HTML report.

Key metrics evaluated:
- Per-base sequence quality (Phred score)
- GC content distribution
- Adapter content
- Overrepresented sequences

"""

# Create environment with FastQC, MultiQC and fastp
!mamba create -n quality -c bioconda fastqc multiqc fastp -y --quiet
!mamba env list

# Create output folders
!mkdir -p fastqc multiqc trimmed

# Run FastQC on all samples
!echo "# Running FastQC"
!mamba run -n quality fastqc ./brca1/*.fq.gz -o ./fastqc --quiet

# Run MultiQC to aggregate reports
!echo "# Running MultiQC"
!mamba run -n quality multiqc ./fastqc -o ./multiqc --quiet

#Download MultiQC report
from google.colab import files
files.download("./multiqc/multiqc_report.html")

"""# STEP 3 — TRIMMING

Step 3 — Read trimming (fastp, Q≥20)

**fastp** performs:
- Automatic adapter detection and removal  
- Quality trimming (Q≥20 threshold)  
- Generation of HTML quality reports before/after trimming
"""

# Trim all three samples (Q≥20, auto adapter detection)
!echo "# Trimming BRCA1_WT"
!mamba run -n quality fastp \
  -i ./brca1/BRCA1_WT_R1.fq.gz \
  -I ./brca1/BRCA1_WT_R2.fq.gz \
  --detect_adapter_for_pe \
  -o ./trimmed/BRCA1_WT_R1_trim.fq.gz \
  -O ./trimmed/BRCA1_WT_R2_trim.fq.gz \
  -h ./trimmed/BRCA1_WT_fastp.html \
  --qualified_quality_phred 20 \
  --thread 4

!echo "# Trimming BRCA1_185delAG"
!mamba run -n quality fastp \
  -i ./brca1/BRCA1_185delAG_R1.fq.gz \
  -I ./brca1/BRCA1_185delAG_R2.fq.gz \
  --detect_adapter_for_pe \
  -o ./trimmed/BRCA1_185delAG_R1_trim.fq.gz \
  -O ./trimmed/BRCA1_185delAG_R2_trim.fq.gz \
  -h ./trimmed/BRCA1_185delAG_fastp.html \
  --qualified_quality_phred 20 \
  --thread 4

!echo "# Trimming BRCA1_c.5266dupC"
!mamba run -n quality fastp \
  -i ./brca1/BRCA1_c.5266dupC_R1.fq.gz \
  -I ./brca1/BRCA1_c.5266dupC_R2.fq.gz \
  --detect_adapter_for_pe \
  -o ./trimmed/BRCA1_c.5266dupC_R1_trim.fq.gz \
  -O ./trimmed/BRCA1_c.5266dupC_R2_trim.fq.gz \
  -h ./trimmed/BRCA1_c.5266dupC_fastp.html \
  --qualified_quality_phred 20 \
  --thread 4

!ls -lh ./trimmed/*.fq.gz

"""# STEP 4 — ALIGNMENT

Step 4 — Alignment (BWA-MEM → sorted, indexed BAM)

**BWA-MEM** aligns reads to the reference genome.  
**Samtools** converts SAM to BAM, sorts by coordinate, and creates an index for fast access.

Read groups (`-R`) are required by GATK and help track sample identity in multi-sample analyses.

Filtrando leituras mapeadas e reconstruindo o genoma por referência (flag **4** no SAM/BAM)
"""

# Create environments for BWA and Samtools
!mamba create -n bwa -c bioconda bwa -y --quiet
!mamba create -n samtools -c bioconda samtools -y --quiet

# Index the reference genome (required before alignment)
!echo "# Indexing reference genome"
!mamba run -n bwa bwa index -p ./refGen/chr17_GRCh38 ./refGen/chr17_GRCh38.fasta

# Create Samtools FASTA index (required by GATK)
!mamba run -n samtools samtools faidx ./refGen/chr17_GRCh38.fasta

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Starting alignment
# mkdir -p aligned
# 
# # Align for each sample
# for SAMPLE in BRCA1_WT BRCA1_185delAG BRCA1_c.5266dupC; do
#   R1="./trimmed/${SAMPLE}_R1_trim.fq.gz"
#   R2="./trimmed/${SAMPLE}_R2_trim.fq.gz"
#   OUT="./aligned/${SAMPLE}.bam"
# 
#   echo "\n--- Aligning ${SAMPLE} ---"
#   mamba run -n bwa bwa mem -M -t 4 \
#     -R "@RG\tID:${SAMPLE}\tSM:${SAMPLE}\tPL:ILLUMINA\tLB:${SAMPLE}_lib1\tPU:${SAMPLE}_unit1" \
#     ./refGen/chr17_GRCh38 $R1 $R2 \
#     -o $OUT
# done

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Starting sort + index + stats for each sample
# 
# for SAMPLE in BRCA1_WT BRCA1_185delAG BRCA1_c.5266dupC; do
#   INPUT_BAM="./aligned/${SAMPLE}.bam"          # Unsorted BAM from previous step
#   SORTED_BAM="./aligned/${SAMPLE}_sorted.bam"  # Output sorted BAM
# 
#   echo "\n--- Sorting ${SAMPLE} ---"
#   # Sort the BAM file by coordinate
#   mamba run -n samtools samtools sort -o $SORTED_BAM $INPUT_BAM
# 
#   echo "--- Indexing ${SAMPLE} ---"
#   # Index the sorted BAM file
#   mamba run -n samtools samtools index $SORTED_BAM
# 
#   echo "--- Flagstat for ${SAMPLE} ---"
#   # Run flagstat on the sorted and indexed BAM
#   mamba run -n samtools samtools flagstat $SORTED_BAM
# done
# 
# echo "\n# Aligned and sorted BAM files:"
# ls -lh ./aligned/*_sorted.bam*

# Criando a pasta para salvar os FASTA das reads mapeadas
!echo -e "# Criando a pasta mapped para salvar os FASTAs\n"
!mkdir -p mapped

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Mapping
# 
# for SAMPLE in BRCA1_WT BRCA1_185delAG BRCA1_c.5266dupC; do
#   INPUT_SORT="./aligned/${SAMPLE}_sorted.bam"
#   OUT_F="./aligned/${SAMPLE}_mapped.bam"
#   OUT_MAPPED="./mapped/${SAMPLE}_mapped_reads.fasta"
# 
#   echo "--- Flag 4 ${SAMPLE} ---"
#   # Removendo flag 4
#   mamba run -n samtools samtools view -b -F 4 \
#   -o $OUT_F $INPUT_SORT
# 
#   echo "--- Saving ${SAMPLE} ---"
#   # Salvando somente as leituras mapeadas (removendo flag 4)
#   mamba run -n samtools samtools fasta \
#   -o $OUT_MAPPED $OUT_F
# 
#   echo "--- Indexing mapped.bam ${SAMPLE} ---"
#   # Indexando os arquivos BAM filtrados
#   mamba run -n samtools samtools index $OUT_F
# 
# done
# 
# ls -lh ./mapped

"""# STEP 5A — GATK

Step 5A — Variant Calling: GATK HaplotypeCaller (GATK Best Practices)

**GATK HaplotypeCaller** reconstructs local haplotypes and identifies SNPs and INDELs.  
The GVCF mode (`-ERC GVCF`) enables scalable multi-sample joint genotyping.

**Workflow:**
1. `HaplotypeCaller` → per-sample GVCF  
2. `CombineGVCFs` → merged cohort GVCF  
3. `GenotypeGVCFs` → final joint-genotyped VCF  
4. `VariantFiltration` → apply quality filters
"""

#Install GATK4
!mamba create -n gatk -c bioconda gatk4 -y --quiet
!mamba list -n gatk gatk4

# Create sequence dictionary (required by GATK)
!echo "# Creating sequence dictionary"
!mamba run -n gatk gatk CreateSequenceDictionary \
  -R /content/refGen/chr17_GRCh38.fasta \
  -O /content/refGen/chr17_GRCh38.dict

!mkdir -p variants/gatk
!echo "# Running HaplotypeCaller (GVCF mode) for each sample"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # Mapping
# 
# for SAMPLE in BRCA1_WT BRCA1_185delAG BRCA1_c.5266dupC; do
#   I_M="./aligned/${SAMPLE}_mapped.bam"
#   O_GATK="./variants/gatk/${SAMPLE}.g.vcf.gz "
# 
#   echo "--- gatk HaplotypeCaller ${SAMPLE} ---"
#   mamba run -n gatk gatk HaplotypeCaller \
#   -R /content/refGen/chr17_GRCh38.fasta \
#   -I $I_M \
#   -O $O_GATK \
#   -ERC GVCF --verbosity ERROR
# done
#

!echo "# Combining GVCFs into cohort"
!mamba run -n gatk gatk CombineGVCFs \
  -R /content/refGen/chr17_GRCh38.fasta \
  -V ./variants/gatk/BRCA1_WT.g.vcf.gz \
  -V ./variants/gatk/BRCA1_185delAG.g.vcf.gz \
  -V ./variants/gatk/BRCA1_c.5266dupC.g.vcf.gz \
  -O ./variants/gatk/cohort.g.vcf.gz \
  --verbosity ERROR

!echo "# Joint genotyping"
!mamba run -n gatk gatk GenotypeGVCFs \
  -R /content/refGen/chr17_GRCh38.fasta \
  -V ./variants/gatk/cohort.g.vcf.gz \
  -O ./variants/gatk/cohort.vcf.gz \
  --verbosity ERROR

!echo "# Applying quality filters (QD, FS, MQ)"
!mamba run -n gatk gatk VariantFiltration \
  -R /content/refGen/chr17_GRCh38.fasta \
  -V ./variants/gatk/cohort.vcf.gz \
  -O ./variants/gatk/cohort_filtered.vcf.gz \
  --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0" \
  --filter-name "GATK_filter" \
  --verbosity ERROR

!echo "# GATK VCF (first variants):"
!zcat ./variants/gatk/cohort_filtered.vcf.gz | grep -v "^##" | head -20

"""# STEP 5B — FREEBAYES

Step 5B — Variant Calling: FreeBayes (alternative approach)

**FreeBayes** is a Bayesian variant caller that works directly from BAM files without the GVCF intermediate step.  
It detects SNPs, INDELs, MNPs and complex variants simultaneously.

**Key advantages over GATK HaplotypeCaller:**
- No GVCF step — simpler single-command workflow  
- Multi-sample calling in one command  
- Flexible allele frequency model (useful for somatic/low-frequency variants)  

**Workflow:**
1. `freebayes` → joint VCF from all BAMs simultaneously  
2. `bcftools filter` → apply quality filter (QUAL ≥ 20)  
3. `bcftools sort` → sort VCF by position
"""

# Install FreeBayes and bcftools
!mamba create -n freebayes -c bioconda freebayes bcftools -y --quiet

!mkdir -p variants/freebayes
!echo "# Running FreeBayes on all samples simultaneously\n"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # FreeBayes calls variants from all BAM files at once (true multi-sample calling)
# mamba run -n freebayes freebayes \
#   -f ./refGen/chr17_GRCh38.fasta \
#   ./aligned/BRCA1_WT_mapped.bam \
#   ./aligned/BRCA1_185delAG_mapped.bam \
#   ./aligned/BRCA1_c.5266dupC_mapped.bam > ./variants/freebayes/cohort_freebayes.vcf

# Index the output VCF
!mamba run -n freebayes bcftools index -t ./variants/freebayes/cohort_freebayes.vcf

!echo "# Filtering variants: QUAL >= 20, keeping SNPs and INDELs only"
!mamba run -n freebayes bash -c \
  'bcftools view -v snps,indels ./variants/freebayes/cohort_freebayes.vcf | \
   bcftools filter -i "QUAL>=20" -Oz -o ./variants/freebayes/cohort_freebayes_filtered.vcf.gz'

!mamba run -n freebayes bcftools index -t ./variants/freebayes/cohort_freebayes_filtered.vcf.gz

!echo "# FreeBayes VCF (first variants):"
!zcat ./variants/freebayes/cohort_freebayes_filtered.vcf.gz | grep -v "^##" | head -20

!mamba run -n freebayes bcftools stats ./variants/freebayes/cohort_freebayes_filtered.vcf.gz > ./variants/freebayes/cohort_freebayes_filtered.stats.txt

from google.colab import files
files.download("./variants/freebayes/cohort_freebayes_filtered.stats.txt")

"""### 🔍 Comparing GATK vs FreeBayes outputs

| Feature | GATK HaplotypeCaller | FreeBayes |
|---------|---------------------|-----------|
| Calling model | Local assembly + HMM | Bayesian allele frequency |
| Multi-sample | GVCF → joint genotyping | Direct multi-BAM input |
| Speed | Slower (GVCFs required) | Faster (one step) |
| Best for | Germline / clinical | Research / flexible |
| Output format | VCF with FILTER field | VCF with QUAL score |

# STEP 6 — ANNOTATION

Step 6 — Variant annotation (bcftools + ClinVar mini)")

**bcftools annotate** adds known variant identifiers and clinical information from external databases.  
Here we use a **ClinVar mini database** (provided in the course repository) to annotate variants with:

- Variant ID (rsID or ClinVar ID)  
- Clinical significance (Pathogenic, Likely Pathogenic, etc.)  
- Associated gene and condition
"""

# Install bcftools (if not already done)
!mamba create -n bcftools -c bioconda bcftools -y --quiet

!mkdir -p annotated

# --- Annotate GATK output ---
!echo "# Annotating GATK VCF with ClinVar mini"
!mamba run -n bcftools bcftools annotate \
  -a ./brca1/clinvar_mini.vcf.gz \
  -c ID,INFO \
  ./variants/gatk/cohort_filtered.vcf.gz \
  -o ./annotated/cohort_gatk_annotated.vcf

# --- Annotate FreeBayes output ---
!echo "# Annotating FreeBayes VCF with ClinVar mini"
!mamba run -n bcftools bcftools annotate \
  -a ./brca1/clinvar_mini.vcf.gz \
  -c ID,INFO \
  ./variants/freebayes/cohort_freebayes_filtered.vcf.gz \
  -o ./annotated/cohort_freebayes_annotated.vcf

!echo "# Annotated GATK VCF:"
!grep -v "^##" ./annotated/cohort_gatk_annotated.vcf | head -20

!echo "# Annotated FreeBayes VCF:"
!grep -v "^##" ./annotated/cohort_freebayes_annotated.vcf | head -20

# Compute statistics for both callers using bcftools stats
!echo "# GATK VCF Statistics"
!mamba run -n bcftools bcftools stats \
  ./variants/gatk/cohort_filtered.vcf.gz | grep -E "^(SN|TSTV)" | head -20

!echo "# FreeBayes VCF Statistics"
!mamba run -n bcftools bcftools stats \
  ./variants/freebayes/cohort_freebayes_filtered.vcf.gz | grep -E "^(SN|TSTV)" | head -20

"""**Summary of what was done:**

| Step | Tool | Output |
|------|------|--------|
| Quality Control | FastQC + MultiQC | HTML reports |
| Trimming | fastp | Cleaned FASTQ |
| Alignment | BWA-MEM + Samtools | Sorted, indexed BAM |
| Variant Calling A | GATK HaplotypeCaller | `cohort_filtered.vcf.gz` |
| Variant Calling B | FreeBayes + bcftools | `cohort_freebayes_filtered.vcf.gz` |
| Annotation | bcftools + ClinVar | Annotated VCF files |
| Statistics | bcftools stats | SNP/INDEL counts, Ts/Tv ratio |

---

### 📁 Output folder structure

```
├── fastqc/          # Per-sample FastQC reports
├── multiqc/         # Aggregated MultiQC report
├── trimmed/         # Quality-trimmed FASTQ files
├── aligned/         # Sorted and indexed BAM files
├── variants/
│   ├── gatk/        # GATK HaplotypeCaller results
│   └── freebayes/   # FreeBayes results
└── annotated/       # VCF files annotated with ClinVar
```

### 🔗 References

- [GATK Best Practices](https://gatk.broadinstitute.org/hc/en-us/sections/360007226651)
- [FreeBayes GitHub](https://github.com/freebayes/freebayes)
- [bcftools documentation](https://www.htslib.org/doc/bcftools.html)
- [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/)
- [Original RSG Brazil 2026 notebook](https://github.com/oncogensus/Curso-RSG-Brazil)
"""